################################################################################
# CryModule.cmake -- helpers for declaring engine modules and header gates.
################################################################################

include_guard(GLOBAL)

# ------------------------------------------------------------------------------
# cry_add_module(<name> SOURCES <...> [INCLUDES <...>] [DEPENDS <...>])
#
# Declares an engine module as a static library. Modules are static rather than
# shared because wasm has no meaningful DLL story -- the engine's DLL-per-module
# layout (CrySystem.dll, CryGame.dll, ...) collapses into one link unit.
# ------------------------------------------------------------------------------
function(cry_add_module name)
    cmake_parse_arguments(ARG "" "" "SOURCES;INCLUDES;DEPENDS" ${ARGN})

    if(NOT ARG_SOURCES)
        message(FATAL_ERROR "cry_add_module(${name}): no SOURCES given")
    endif()

    add_library(${name} STATIC ${ARG_SOURCES})
    cry_apply_common_settings(${name})

    if(ARG_INCLUDES)
        target_include_directories(${name} PUBLIC ${ARG_INCLUDES})
    endif()
    if(ARG_DEPENDS)
        target_link_libraries(${name} PUBLIC ${ARG_DEPENDS})
    endif()

    list(LENGTH ARG_SOURCES _n)
    message(STATUS "cry: module ${name} (${_n} sources)")
endfunction()

# ------------------------------------------------------------------------------
# cry_add_header_gate(<name> HEADERS <...> [INCLUDES <...>])
#
# Some modules -- CryCommon above all -- are pure interface: headers with no
# translation units of their own. A header that is never compiled is never
# validated, so we synthesise one TU per header.
#
# Compiling each header in isolation (rather than all of them in one TU) is
# deliberate: it proves each header is self-contained, and it turns "the port
# builds / does not build" into a countable per-header score we can work down.
# ------------------------------------------------------------------------------
function(cry_add_header_gate name)
    cmake_parse_arguments(ARG "" "" "HEADERS;INCLUDES" ${ARGN})

    set(_gendir "${CMAKE_CURRENT_BINARY_DIR}/headergate")
    file(MAKE_DIRECTORY "${_gendir}")

    set(_tus "")
    foreach(_hdr IN LISTS ARG_HEADERS)
        get_filename_component(_stem "${_hdr}" NAME_WE)
        set(_tu "${_gendir}/hg_${_stem}.cpp")

        # platform.h must come first: it establishes the MSVC-keyword shims
        # (__forceinline, __cdecl, ...) and the DWORD/LPVOID typedefs that every
        # other header assumes are already in scope.
        file(WRITE "${_tu}"
            "// Generated by cry_add_header_gate(). Do not edit.\n"
            "// Validates that <${_hdr}> is self-contained under clang/wasm.\n"
            "#include <platform.h>\n"
            "#include \"${_hdr}\"\n")
        list(APPEND _tus "${_tu}")
    endforeach()

    add_library(${name} OBJECT ${_tus})
    cry_apply_common_settings(${name})
    if(ARG_INCLUDES)
        target_include_directories(${name} PRIVATE ${ARG_INCLUDES})
    endif()

    list(LENGTH ARG_HEADERS _n)
    message(STATUS "cry: header gate ${name} (${_n} headers)")
endfunction()
