################################################################################
# CryModule.cmake -- helpers for declaring engine modules and header gates.
################################################################################

include_guard(GLOBAL)

# ------------------------------------------------------------------------------
# cry_add_module(<name> SOURCES <...> [INCLUDES <...>] [DEPENDS <...>])
#
# Declares an engine module as a static library. Modules are static rather than
# shared because wasm has no meaningful DLL story -- the engine's DLL-per-module
# layout (CrySystem.dll, CryGame.dll, ...) collapses into one link unit.
# ------------------------------------------------------------------------------
function(cry_add_module name)
    cmake_parse_arguments(ARG "" "" "SOURCES;INCLUDES;DEPENDS" ${ARGN})

    if(NOT ARG_SOURCES)
        message(FATAL_ERROR "cry_add_module(${name}): no SOURCES given")
    endif()

    add_library(${name} STATIC ${ARG_SOURCES})
    cry_apply_common_settings(${name})

    if(ARG_INCLUDES)
        target_include_directories(${name} PUBLIC ${ARG_INCLUDES})
    endif()
    if(ARG_DEPENDS)
        target_link_libraries(${name} PUBLIC ${ARG_DEPENDS})
    endif()

    list(LENGTH ARG_SOURCES _n)
    message(STATUS "cry: module ${name} (${_n} sources)")
endfunction()

# ------------------------------------------------------------------------------
# cry_add_header_gate(<name> HEADERS <...> [INCLUDES <...>])
#
# Some modules -- CryCommon above all -- are pure interface: headers with no
# translation units of their own. A header that is never compiled is never
# validated, so we synthesise one TU per header.
#
# Compiling each header in isolation (rather than all of them in one TU) is
# deliberate: it proves each header is self-contained, and it turns "the port
# builds / does not build" into a countable per-header score we can work down.
# ------------------------------------------------------------------------------
function(cry_add_header_gate name)
    cmake_parse_arguments(ARG "" "" "HEADERS;INCLUDES" ${ARGN})

    set(_gendir "${CMAKE_CURRENT_BINARY_DIR}/headergate")
    file(MAKE_DIRECTORY "${_gendir}")

    set(_tus "")
    foreach(_hdr IN LISTS ARG_HEADERS)
        get_filename_component(_stem "${_hdr}" NAME_WE)
        set(_tu "${_gendir}/hg_${_stem}.cpp")

        # platform.h must come first: it establishes the MSVC-keyword shims
        # (__forceinline, __cdecl, ...) and the DWORD/LPVOID typedefs that every
        # other header assumes are already in scope.
        file(WRITE "${_tu}"
            "// Generated by cry_add_header_gate(). Do not edit.\n"
            "// Validates that <${_hdr}> is self-contained under clang/wasm.\n"
            "#include <platform.h>\n"
            "#include \"${_hdr}\"\n")
        list(APPEND _tus "${_tu}")
    endforeach()

    add_library(${name} OBJECT ${_tus})
    cry_apply_common_settings(${name})
    if(ARG_INCLUDES)
        target_include_directories(${name} PRIVATE ${ARG_INCLUDES})
    endif()

    list(LENGTH ARG_HEADERS _n)
    message(STATUS "cry: header gate ${name} (${_n} headers)")
endfunction()

# ------------------------------------------------------------------------------
# cry_link_module_group(<target> <libs...>)
#
# Links the engine's mutually recursive static libraries.
#
# The modules reference each other in cycles -- CrySystem calls into
# Cry3DEngine, which calls back into CrySystem -- which was free when each was
# its own DLL and the dynamic loader resolved everything at runtime. As static
# archives it is not free: GNU ld walks the link line once, left to right, and
# will not revisit an archive it has already passed. No ordering satisfies the
# cycles, so the whole set is wrapped in --start-group/--end-group, which tells
# ld to keep re-scanning until nothing new resolves.
#
# wasm-ld needs none of that and does not implement it. It resolves the whole
# program's symbol table at once rather than in one pass over the command line,
# so archive order is irrelevant there and asking for RESCAN is an error.
# ------------------------------------------------------------------------------
function(cry_link_module_group target)
    if(EMSCRIPTEN)
        target_link_libraries(${target} PRIVATE ${ARGN})
    elseif(CMAKE_VERSION VERSION_GREATER_EQUAL 3.24)
        target_link_libraries(${target} PRIVATE "$<LINK_GROUP:RESCAN,${ARGN}>")
    else()
        # LINK_GROUP arrived in CMake 3.24. Older versions get the flags spelled out.
        target_link_libraries(${target} PRIVATE
            -Wl,--start-group ${ARGN} -Wl,--end-group)
    endif()
endfunction()
